export const TAB_PAGES: any[] = [
  {
    title: 'Ingresar',
    tab: 'auth',
    icon: 'log-in',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Verique su correo',
    tab: 'verify-email',
    icon: 'log-in',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Inicio',
    tab: 'list-reports',
    icon: 'document',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Extraviados',
    tab: 'extravied',
    icon: 'scan-circle',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Encontrados',
    tab: 'finded',
    icon: 'locate',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Adopciones',
    tab: 'adoptions-list',
    icon: 'paw',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Servicios',
    tab: 'services',
    icon: 'briefcase',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Mis reportes',
    tab: 'my-reports',
    icon: 'clipboard',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Favoritos',
    tab: 'my-favorite',
    icon: 'heart',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Busca en tu zona',
    tab: 'search-zone',
    icon: 'map',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Ubicación',
    tab: 'map-report',
    icon: 'map',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Reportar',
    tab: 'create-report-new',
    icon: 'clipboard',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Reportar',
    tab: `create-report`,
    icon: 'clipboard',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Chats',
    tab: 'my-chats',
    icon: 'chatbubble-ellipses',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Notificaciones',
    tab: 'notification',
    icon: 'chatbox-ellipses',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Mi cuenta',
    tab: 'profile',
    icon: 'person',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Chat',
    tab: 'chat',
    icon: 'chatbubble-ellipses',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  // {
  //   title: 'Donaciones',
  //   tab: 'donations',
  //   icon: 'cash',
  //   inSidemenu: true,
  //   inTabBar: false,
  //   showTabBar: true,
  // },
  {
    title: 'Ayuda',
    tab: 'support',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Login',
    tab: 'login',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Registro',
    tab: 'register',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Reporte',
    tab: 'view-report',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Recuperar Password',
    tab: 'recovery-password',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Cerrar sesión',
    tab: 'log-out',
    icon: 'log-out',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Formulario Organización',
    tab: 'organization-form',
    icon: 'register',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
];

const TAB_PAGES_LOGGED: any[] = [
  {
    title: 'Ingresar',
    tab: 'auth',
    icon: 'log-in',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Verique su correo',
    tab: 'verify-email',
    icon: 'log-in',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Inicio',
    tab: 'list-reports',
    icon: 'document',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Extraviados',
    tab: 'extravied',
    icon: 'scan-circle',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Encontrados',
    tab: 'finded',
    icon: 'locate',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Adopciones',
    tab: 'adoptions-list',
    icon: 'paw',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Servicios',
    tab: 'services',
    icon: 'briefcase',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Mis reportes',
    tab: 'my-reports',
    icon: 'clipboard',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Favoritos',
    tab: 'my-favorite',
    icon: 'heart',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Busca en tu zona',
    tab: 'search-zone',
    icon: 'map',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Ubicación',
    tab: 'map-report',
    icon: 'map',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Reportar',
    tab: 'create-report-new',
    icon: 'clipboard',
    inSidemenu: false,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Reportar',
    tab: `create-report`,
    icon: 'clipboard',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Chats',
    tab: 'my-chats',
    icon: 'chatbubble-ellipses',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Notificaciones',
    tab: 'notification',
    icon: 'chatbox-ellipses',
    inSidemenu: true,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Mi cuenta',
    tab: 'profile',
    icon: 'person',
    inSidemenu: true,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Chat',
    tab: 'chat',
    icon: 'chatbubble-ellipses',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Donaciones',
    tab: 'donations',
    icon: 'cash',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
    showAndroid: true,
  },
  {
    title: 'Ayuda',
    tab: 'support',
    icon: 'headset',
    inSidemenu: true,
    inTabBar: true,
    showTabBar: true,
  },
  {
    title: 'Login',
    tab: 'login',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Registro',
    tab: 'register',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Reporte',
    tab: 'view-report',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Recuperar Password',
    tab: 'recovery-password',
    icon: 'headset',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Formulario Organización',
    tab: 'organization-form',
    icon: 'register',
    inSidemenu: false,
    inTabBar: false,
    showTabBar: true,
  },
  {
    title: 'Administrar Publicidad',
    tab: 'admin-ads',
    icon: 'megaphone',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
    requiresAdminAuth: true
  },
  {
    title: 'Cerrar sesión',
    tab: 'log-out',
    icon: 'log-out',
    inSidemenu: true,
    inTabBar: false,
    showTabBar: true,
  },
];

export const TABS_ROOT: string = 'main-tab';

export const APP_PAGES_LOGGED: any[] = TAB_PAGES_LOGGED.map((page: any) => {
  page.url = '/' + TABS_ROOT + '/' + page.tab;
  return page;
});

export const APP_PAGES: any[] = TAB_PAGES.map((page: any) => {
  page.url = '/' + TABS_ROOT + '/' + page.tab;
  return page;
});
